%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/studyroom/EOSC_lab/Lab1_part2/monthly_maunaloa_co2.csv
%
% Auto-generated by MATLAB on 20-Jan-2021 10:29:17

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = [58, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Yr", "Mn", "Date", "Date1", "CO2", "seasonally", "fit", "seasonally1", "CO3", "seasonally2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Yr", "Mn", "Date", "Date1", "CO2", "seasonally", "fit", "seasonally1", "CO3", "seasonally2"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable("/Users/studyroom/EOSC_lab/Lab1_part2/monthly_maunaloa_co2.csv", opts);

%% Convert to output type
Yr = tbl.Yr;
Mn = tbl.Mn;
Date = tbl.Date;
Date1 = tbl.Date1;
CO2 = tbl.CO2;
seasonally = tbl.seasonally;
fit = tbl.fit;
seasonally1 = tbl.seasonally1;
CO3 = tbl.CO3;
seasonally2 = tbl.seasonally2;

%% Question 1 - Clear temporary variables
clear opts tbl

fid = fopen('monthly_maunaloa_co2.csv');
format = '%f %f %f %f %f %f %f %f %f %f';
mauna_loa_data = textscan(fid, format, 'HeaderLines', 57, ...
'Delimiter', ',');
co2_date = mauna_loa_data{4};
co2 = mauna_loa_data{5};
mask = co2 > 0;
plot(co2_date(mask),co2(mask));
xlabel('Date (years)')
ylabel('Measured CO2 (ppm)')
title('Date vs Measured CO2')
axis([1955 2015 310 395])
saveas(gcf,'figure_q1_lab1b_erichsieh.jpg')

%% Question 2 - Clear temporary variables
clc
clear all
clear

M = load('MEI_data_only.txt');
% ommit the year column
N = M(:, 2:end);
% set the length of dataset
len = 756;
% reshape Matrix to a single column
mei = reshape(N', [len 1]);
% empty vector
my_datevectors = [];
row = 0;
% generate dates into my_datevectors
for year=1950:2012
    for month=1:1:12
        row = row + 1;
        my_datevectors(row, :)=[year month 1 0 0 0];
    end
end
% convert datevectors [yyy mm dd ...] to computer-readable data
my_datenumbers = datenum(my_datevectors);
plot(my_datenumbers, mei);
datetick
xlabel('Date (years)')
ylabel('MEI Index')
title('MEI Index vs Date (years)')
saveas(gcf,'figure_q2_lab1b_erichsieh.jpg')

%% Question 3
clc
clear all
close
M = load('n2o.txt');
% load data points only
n2o = M(:, 4);
% empty vector
my_datevectors = [];
row = 0;
% generate dates into my_datevectors
for year=2001:2020
    for month=1:1:12
        row = row + 1;
        my_datevectors(row, :)=[year month 1 0 0 0];
    end
end
% convert datevectors [yyy mm dd ...] to computer-readable data
my_datenumbers = datenum(my_datevectors);
plot(my_datenumbers, n2o);
datetick
xlabel('Date (years)')
ylabel('N_2O Mole Fraction (ppb)')
title('N_2O Monthly Means vs Date (years)')
saveas(gcf,'figure_q3_lab1b_erichsieh.jpg')